name: Print Test Secret

on:
  push:
    branches:
      - main  # Change this to your desired branch

jobs:
  print-secret:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Print MANISH Secret
        run: |
          echo "value of Manish is" >> abc.txt
          echo "MANISH Secret: ${{ secrets.STAGING }}" >> abc.txt
          cat abc.txt