name: Print Test Secret

on:
  push:
    branches:
      - main  # Change this to your desired branch

jobs:
  print-secret:
    runs-on: ubuntu-latest
    environment: staging  # Specify the environment here

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Print MANISH Secret
        run: |
          echo "value of Manish is" >> abc.txt
          echo "MANISH Secret: ${{ secrets.MANISH }}" >> abc.txt
          cat abc.txt
      - name: Debug Environment
        run: |
          echo "Environment: ${{ github.environment }}"
          echo "Secrets: ${{ secrets }}"
      - name: Debug Secrets
        run: |
          echo "Defined secrets:"
          for secret in $(compgen -v | grep '^SECRET_'); do
            echo $secret
          done
