name: Print Test Secret

on:
  push:
    branches:
      - main

jobs:
  print-secret:
    runs-on: ubuntu-latest
    environment: staging

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Print Test Secret
        run: |
          echo "Test Secret: ${{ secrets.staging }}" >> abc.txt
          cat abc.txt