name: Print Test Secret

on:
  push:
    branches:
      - main  # Change this to your desired branch

jobs:
  print-secret:
    runs-on: Manish

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Save JSON to File
        run: |
          cd /home/laravel
          echo '${{ secrets.STAGING }}' > staging.json
          cat staging.json
      