name: Print Test Secret

on:
  push:
    branches:
      - main  # Change this to your desired branch

jobs:
  print-secret:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Save JSON to File
        run: |
          cd /home/laravel
          > staging.json
          echo '${{ secrets.STAGING }}' > staging.json
          cat staging.json
      - name: Convert JSON to .env
        run: |
          cd /home/laravel
          jq -r 'to_entries | .[] | "\(.key)=\(.value)"' staging.json > .env
          echo ".env file created with the following keys:"
          cat .env | awk -F= '{print $1}'
        